### ISSUE TITLE
Story "Setup Application Framework"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents#55]
# Story "Setup Application Framework"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA developer, I want to have a framework to build and deploy managed applications like or within the SDE (https://github.com/eclipse-tractusx/managed-simple-data-exchanger consisting of https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend and https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend).

## Acceptance Criteria

- Find out how deployment of applications in the portal works
- Find out how managed application frontend find their backend
- Find out how managed backends find their EDC (especially: the agent/data plane if needed)
- Implement a sample page with uses a simple EDC call.
 
## Estimation 

8 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/278#issuecomment-1770871136_

**Comment by drcgjung** [comment]
won't do
