### ISSUE TITLE
Story "Implement Simple Graph Exchanger Backend"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents#57]
# Story "Implement Simple Graph Exchanger Backend"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA frontend developer, I want to have an implementation of the SGE API in order to bring my application alive.

## Acceptance Criteria

- API implementation on top of the agent plane
 
## Estimation 

8 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/278#issuecomment-1770880777_

**Comment by drcgjung** [comment]
won't do
