### ISSUE TITLE
Story "Implement Simple Graph Exchanger Frontend"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents#58]
# Story "Implement Simple Graph Exchanger Frontend"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA user, I want to have a ready-made frontend to the SGE API.

## Acceptance Criteria

- Implementation of the wireframe using the backend API

## Estimation 

8 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/278#issuecomment-1770883062_

**Comment by drcgjung** [comment]
won't do
