### ISSUE TITLE
Story "Bundle SGE application"

### ISSUE THREAD

**Issue by igorsvetlov** [eclipse-tractusx/knowledge-agents#59]
# Story "Bundle SGE application"

Repository https://github.com/eclipse-tractusx/knowledge-agents

## Statement 

As KA deployer, I want to have a ready-made chart of the SGE in order to deploy it.

## Acceptance Criteria

- Bundle deployment of frontend and backend

## Estimation 

4 SP

_Originally posted by @drcgjung in https://github.com/eclipse-tractusx/sig-release/issues/278#issuecomment-1770885682_

**Comment by drcgjung** [comment]
won't do
